Question 1: What is Generative AI and what are its primary use cases across
industries?
- Generative AI is a type of artificial intelligence that can create new content such as text, images, audio, video, code, or even synthetic data by learning patterns from existing data.
It uses advanced models like Large Language Models (LLMs), GANs (Generative Adversarial Networks), VAEs (Variational Autoencoders), and Transformers to generate outputs that look human-created.
- 1. IT & Software Development
   - Code generation and debugging
   - Automated documentation
   - Test case generation
   - API generation and refactoring
- 2. Business & Enterprise
   - Report writing, summaries, and automation
   - Creating presentations, business insights
   - Customer support chatbots
   - Virtual assistants
- 3. Healthcare
   - Medical report generation
   - Drug discovery (molecule generation)
   - Synthesizing patient data for research
   - Medical imaging enhancement
- 4. Education
   - Personalized learning content
   - Automated assignments and quizzes
   - Language tutoring
   - Learning materials generation (notes, explanations)
- 5. Finance
   - Risk modeling with synthetic data
   - Fraud detection patterns
   - Automated financial summaries
   - Personalized financial advice
- 6. Marketing & Advertising
  - Social media content creation
  - Ad copy generation
  - Market trend prediction
  - Customer segmentation using synthetic data

Question 2: Explain the role of probabilistic modeling in generative models. How do
these models differ from discriminative models?
- Role of Probabilistic Modeling in Generative Models
- 1. Models the data generation process
   - Generative models try to understand how the data is created, using probability distributions.
- 2. Learns joint probability P(X, Y)
   - They learn both features (X) and labels (Y) together.
- 3. Enables sampling of new data
   - Once the probability distribution is learned, the model can generate new examples by sampling.
- 4 Captures hidden/latent structure
- 5. Handles missing or incomplete data
- 6. Useful for unsupervised learning
- How Generative Models Differ from Discriminative Models
  - 1. What they learn
  - 2. Data generation
  - 3. Type of tasks
  - 4. Complexity
  - 5. Accuracy
  - 6. Decision boundaries
  - 7. Training data requirement
  - 8. Using unlabeled data
  - 9. Robustness


Question 3: What is the difference between Autoencoders and Variational
Autoencoders (VAEs) in the context of text generation?

- 1. Autoencoders (AEs)
- An Autoencoder is a neural network that learns to compress input data into a lower-dimensional representation (encoder) and then reconstruct the original data (decoder).
- How Autoencoders work for text
  - They convert text into embeddings.
  - Encode → latent vector → decode back to the input text.
  - Goal = minimize reconstruction loss
- Key characteristics
  - Deterministic latent space
  - Map each input to a fixed latent vector
  - Great for feature extraction
  - Great for noise removal (denoising autoencoders)
- 2. Variational Autoencoders (VAEs)
- A VAE is a probabilistic version of an autoencoder that learns a distribution over latent space instead of fixed vectors.
- How VAEs work for text
    - Encoder outputs mean (μ) and variance (σ²) for each input.
    - Latent representation is a sample from N(μ, σ²).
    - Decoder generates text from these sampled latent vectors.
- Key characteristics
    - Latent space is continuous and smooth
    - Can generate new sentences by sampling from the learned distribution
    - Encourages generalization
    - Adds regularization (KL Divergence) to shape the latent space
- Why VAEs are better for text generation
    - They model how text varies probabilistically.
    - Any point in latent space can decode into a meaningful sentence.

Question 4: Describe the working of attention mechanisms in Neural Machine
Translation (NMT). Why are they critical?
- 1. What is Attention in NMT?
   - In Neural Machine Translation, an attention mechanism allows the model to focus on specific words in the source sentence when generating each word in the target sentence.
   - Instead of compressing the entire input sentence into a single fixed-size vector, attention gives the model a dynamic, context-dependent representation for each output word.
- 2. How Attention Works
   - Step 1: Encoder processes the source sentence
      - The encoder (RNN/LSTM/GRU/Transformer) reads each word of the source sentence.
      - It produces hidden states (h₁, h₂, h₃… hₙ) for each input word.
    - Step 2: Decoder generates the target sentence
       - When producing a word in the target language, the decoder needs relevant information from the source.
    - Step 3: Compute alignment scores
      - For each decoder step, the model calculates a score for each encoder hidden state:
      - score = alignment(decoder_state, encoder_hidden_state)
    - Step 4: Convert scores into attention weights
       - Alignment scores are normalized using Softmax.
       - They become attention weights (α₁, α₂, α₃… αₙ), summing to 1.
    - Step 5: Create a context vector
       - The model computes a weighted sum:
       - context = Σ (attention_weight × encoder_hidden_state)
    - Step 6: Decoder uses context + its state to produce the target word
       - the context vector
       - the decoder’s previous hidden state

Question 5: What ethical considerations must be addressed when using generative AI
for creative content such as poetry or storytelling?
- 1. Copyright and Intellectual Property
  - AI models are trained on large datasets that may include copyrighted books, poems, and stories.
  - Generated content may unintentionally resemble existing works.
- 2. Originality and Creativity Concerns
  - AI can only remix what it has learned; it does not create from lived experiences.
  - Using AI for poetry/storytelling may devalue human creativity.
  - Ethical issue: replacing human writers with AI-generated content without acknowledgment.
- 3. Bias and Stereotypes
  - Gender stereotypes
  - Cultural insensitivity
  - Harmful tropes in stories
- 4. Misinformation and Fabrication
  - AI-generated stories may be misinterpreted as factual.
  - If AI produces realistic-looking content (e.g., historical stories), it can distort facts.
  - Ethical issue: separating fiction from reality.
- 5. Lack of Attribution and Transparency
   - Users may present AI-written content as their own without disclosure.
   - Important to state when content is AI-assisted.
   - Many industries (education, journalism) require transparency.
- 6. Overreliance and Loss of Human Creativity
   - critical thinking
   - writing skill development
   - creative imagination
- 7. Deepfake Text and Manipulation
   - Generative AI can produce convincing narratives that manipulate emotions.
   - Used for propaganda, political manipulation, or spreading fake stories
- 8. Cultural Appropriation Issues
   - AI may generate stories or poems using cultural elements it does not fully understand.
   - It may disrespect sacred traditions or indigenous narratives.
- 9. Quality and Ethical Training Data
   - pirated books
   - fanfiction
   - copyrighted poems
   - personal blogs

Question 6: Use the following small text dataset to train a simple Variational
Autoencoder (VAE) for text reconstruction:
["The sky is blue", "The sun is bright", "The grass is green",
"The night is dark", "The stars are shining"]

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

texts = [
    "The sky is blue",
    "The sun is bright",
    "The grass is green",
    "The night is dark",
    "The stars are shining"
]

# Tokenization
tokenizer = Tokenizer(lower=True)
tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)
maxlen = max(len(s) for s in sequences)

# Padding
padded = pad_sequences(sequences, maxlen=maxlen, padding='post')

vocab_size = len(tokenizer.word_index) + 1

print("Padded sequences:\n", padded)
print("Vocabulary size:", vocab_size)

Padded sequences:
 [[ 1  3  2  4]
 [ 1  5  2  6]
 [ 1  7  2  8]
 [ 1  9  2 10]
 [ 1 11 12 13]]
Vocabulary size: 14


Question 7: Use a pre-trained GPT model (like GPT-2 or GPT-3) to translate a short
English paragraph into French and German. Provide the original and translated text.

In [14]:
!pip install transformers sentencepiece

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

english_text = """
The weather today is beautiful. The sun is shining and people are enjoying
their time outside. It is a perfect day for a walk in the park.
"""

print("Original English Paragraph:\n", english_text)

# -----------------------------------------
# English → French
# -----------------------------------------
tokenizer_fr = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-fr")
model_fr = AutoModelForSeq2SeqLM.from_pretrained("Helsinki-NLP/opus-mt-en-fr")

inputs = tokenizer_fr.encode(english_text, return_tensors="pt")
outputs = model_fr.generate(inputs, max_length=200)
french_translation = tokenizer_fr.decode(outputs[0], skip_special_tokens=True)

print("\nFrench Translation:\n", french_translation)

# -----------------------------------------
# English → German
# -----------------------------------------
tokenizer_de = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-de")
model_de = AutoModelForSeq2SeqLM.from_pretrained("Helsinki-NLP/opus-mt-en-de")

inputs = tokenizer_de.encode(english_text, return_tensors="pt")
outputs = model_de.generate(inputs, max_length=200)
german_translation = tokenizer_de.decode(outputs[0], skip_special_tokens=True)

print("\nGerman Translation:\n", german_translation)

Original English Paragraph:
 
The weather today is beautiful. The sun is shining and people are enjoying
their time outside. It is a perfect day for a walk in the park.



Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning



French Translation:
 Le temps d'aujourd'hui est beau. Le soleil brille et les gens profitent de leur temps à l'extérieur. C'est une journée parfaite pour une promenade dans le parc.


Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning



German Translation:
 Das Wetter heute ist schön. Die Sonne scheint und die Menschen genießen ihre Zeit draußen. Es ist ein perfekter Tag für einen Spaziergang im Park.


Question 8: Implement a simple attention-based encoder-decoder model for
English-to-Spanish translation using Tensorflow or PyTorch.

In [15]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np

# --------------------------
# 1. Tiny English–Spanish Dataset
# --------------------------
english_sentences = [
    "hello",
    "how are you",
    "i am fine",
    "what is your name",
    "nice to meet you",
]

spanish_sentences = [
    "hola",
    "como estas",
    "estoy bien",
    "cual es tu nombre",
    "encantado de conocerte",
]

# Add start/end tokens for decoder targets
spanish_sentences_in  = ["<start> " + s for s in spanish_sentences]
spanish_sentences_out = [s + " <end>" for s in spanish_sentences]

# --------------------------
# 2. Tokenization
# --------------------------
eng_tok = Tokenizer()
eng_tok.fit_on_texts(english_sentences)

spa_tok = Tokenizer()
spa_tok.fit_on_texts(spanish_sentences_in + spanish_sentences_out)

eng_seq = eng_tok.texts_to_sequences(english_sentences)
spa_seq_in = spa_tok.texts_to_sequences(spanish_sentences_in)
spa_seq_out = spa_tok.texts_to_sequences(spanish_sentences_out)

max_eng = max(len(s) for s in eng_seq)
max_spa = max(len(s) for s in spa_seq_in)

eng_seq = pad_sequences(eng_seq, maxlen=max_eng, padding="post")
spa_seq_in = pad_sequences(spa_seq_in, maxlen=max_spa, padding="post")
spa_seq_out = pad_sequences(spa_seq_out, maxlen=max_spa, padding="post")

eng_vocab = len(eng_tok.word_index) + 1
spa_vocab = len(spa_tok.word_index) + 1

# --------------------------
# 3. Bahdanau Attention Layer
# --------------------------
class BahdanauAttention(tf.keras.layers.Layer):
    def __init__(self, units):
        super().__init__()
        self.W1 = Dense(units)
        self.W2 = Dense(units)
        self.V  = Dense(1)

    def call(self, hidden, enc_output):
        hidden_with_time = tf.expand_dims(hidden, 1)
        score = self.V(tf.nn.tanh(self.W1(enc_output) + self.W2(hidden_with_time)))
        weights = tf.nn.softmax(score, axis=1)
        context = weights * enc_output
        context = tf.reduce_sum(context, axis=1)
        return context, weights

# --------------------------
# 4. Encoder
# --------------------------
class Encoder(tf.keras.Model):
    def __init__(self, vocab_size, embed_dim, units):
        super().__init__()
        self.embed = Embedding(vocab_size, embed_dim)
        self.lstm  = LSTM(units, return_sequences=True, return_state=True)

    def call(self, x):
        x = self.embed(x)
        output, h, c = self.lstm(x)
        return output, h, c

# --------------------------
# 5. Decoder with Attention
# --------------------------
class Decoder(tf.keras.Model):
    def __init__(self, vocab_size, embed_dim, units):
        super().__init__()
        self.embed = Embedding(vocab_size, embed_dim)
        self.lstm  = LSTM(units, return_sequences=True, return_state=True)
        self.attn  = BahdanauAttention(units)
        self.fc    = Dense(vocab_size)

    def call(self, x, hidden, enc_output):
        context, attn_weights = self.attn(hidden, enc_output)
        x = self.embed(x)
        x = tf.concat([tf.expand_dims(context, 1), x], axis=-1)
        output, h, c = self.lstm(x)
        logits = self.fc(output)
        return logits, h, c, attn_weights

# --------------------------
# 6. Build Model
# --------------------------
embed_dim = 64
units = 128

encoder = Encoder(eng_vocab, embed_dim, units)
decoder = Decoder(spa_vocab, embed_dim, units)

optimizer = tf.keras.optimizers.Adam()

loss_obj = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

# --------------------------
# 7. Train Step
# --------------------------
@tf.function
def train_step(inp, targ_in, targ_out):
    loss = 0
    with tf.GradientTape() as tape:
        enc_output, h, c = encoder(inp)

        dec_h, dec_c = h, c
        for t in range(targ_out.shape[1]):
            predictions, dec_h, dec_c, _ = decoder(
                targ_in[:, t:t+1], dec_h, enc_output
            )
            loss += loss_obj(targ_out[:, t], predictions[:, 0, :])

    variables = encoder.trainable_variables + decoder.trainable_variables
    grads = tape.gradient(loss, variables)
    optimizer.apply_gradients(zip(grads, variables))
    return loss / targ_out.shape[1]

# --------------------------
# 8. Train Model
# --------------------------
EPOCHS = 50
for e in range(EPOCHS):
    loss = train_step(eng_seq, spa_seq_in, spa_seq_out)
    if (e + 1) % 10 == 0:
        print(f"Epoch {e+1}, Loss: {loss.numpy():.4f}")

# --------------------------
# 9. Translation Function
# --------------------------
def translate(sentence):
    seq = eng_tok.texts_to_sequences([sentence])
    seq = pad_sequences(seq, maxlen=max_eng, padding="post")

    enc_output, h, c = encoder(seq)
    dec_h, dec_c = h, c

    dec_input = tf.expand_dims([spa_tok.word_index["<start>"]], 0)
    result = ""

    for _ in range(max_spa):
        predictions, dec_h, dec_c, _ = decoder(dec_input, dec_h, enc_output)
        predicted_id = tf.argmax(predictions[0, 0]).numpy()
        if predicted_id == 0:
            break
        word = spa_tok.index_word.get(predicted_id, "")
        if word == "<end>":
            break
        result += word + " "
        dec_input = tf.expand_dims([predicted_id], 0)

    return result.strip()

Epoch 10, Loss: 2.6389
Epoch 20, Loss: 2.3597
Epoch 30, Loss: 1.9705
Epoch 40, Loss: 1.7379
Epoch 50, Loss: 1.5020


Question 9: Use the following short poetry dataset to simulate poem generation with a
pre-trained GPT model:
["Roses are red, violets are blue,",
"Sugar is sweet, and so are you.",
"The moon glows bright in silent skies,",
"A bird sings where the soft wind sighs."]

In [16]:
!pip install transformers torch -q

from transformers import GPT2Tokenizer, GPT2LMHeadModel
import torch

# -------------------------------
# 1. Poetry Dataset
# -------------------------------
poems = [
    "Roses are red, violets are blue,",
    "Sugar is sweet, and so are you.",
    "The moon glows bright in silent skies,",
    "A bird sings where the soft wind sighs.",
]

dataset_text = "\n".join(poems)

# -------------------------------
# 2. Load Pre-trained GPT-2
# -------------------------------
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")

inputs = tokenizer.encode(dataset_text, return_tensors="pt")

# -------------------------------
# 3. Generate Text
# -------------------------------
output = model.generate(
    inputs,
    max_length=120,
    num_beams=5,
    no_repeat_ngram_size=2,
    early_stopping=True,
)

generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
print("Generated Poem:\n")
print(generated_text)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  | 
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


Generated Poem:

Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.


It's a beautiful day, but it's not the day you want it to be. It's the one you don't want to see. The one that you're afraid of. You're scared of what you'll see in the future. That's why I'm here. I want you to know that I love you and I will never let you down. And I


Question 10: Imagine you are building a creative writing assistant for a publishing
company. The assistant should generate story plots and character descriptions using
Generative AI. Describe how you would design the system, including model selection,
training data, bias mitigation, and evaluation methods. Explain the real-world challenges
you might face

In [17]:
!pip install transformers torch -q

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

# Load GPT-2
model_name = "gpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer
)

# Simple bias filter
BAD = ["racist","sexist","kill","hate","abuse","violent"]

def safe(text):
    return not any(b in text.lower() for b in BAD)


# --- FIXED FUNCTIONS ---

def generate_story_plot(genre, tone, world_setting):
    prompt = f"""
Generate a creative story plot.

Genre: {genre}
Tone: {tone}
World Setting: {world_setting}

Write a 3-paragraph plot:
"""
    result = generator(
        prompt,
        max_new_tokens=150,      # ← FIXED
        do_sample=True,
        temperature=0.9,
        top_p=0.9
    )[0]["generated_text"]

    return result if safe(result) else "[BLOCKED BY SAFETY FILTER]"


def generate_character_description(name, role, personality):
    prompt = f"""
Create a character description.

Name: {name}
Role: {role}
Personality: {personality}

Describe:
- appearance
- background
- motivations
- flaws
"""
    result = generator(
        prompt,
        max_new_tokens=150,      # ← FIXED
        do_sample=True,
        temperature=0.9,
        top_p=0.9
    )[0]["generated_text"]

    return result if safe(result) else "[BLOCKED BY SAFETY FILTER]"


def evaluate_output(text):
    words = text.split()
    return {
        "length": len(words),
        "unique_words": len(set(words)),
        "avg_word_length": sum(len(w) for w in words) / len(words)
    }


# --- RUN THE GENERATOR ---

print("\n=== STORY PLOT ===\n")
story = generate_story_plot(
    "Fantasy",
    "Mysterious & adventurous",
    "An ancient forest hiding forgotten magic"
)
print(story)

print("\n=== CHARACTER DESCRIPTION ===\n")
character = generate_character_description(
    "Elara Stormwind",
    "Protagonist ranger",
    "Brave, introverted, analytical, compassionate"
)
print(character)

print("\n=== EVALUATION ===\n")
print(evaluate_output(story))

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  | 
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=150) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)



=== STORY PLOT ===



Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=150) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)



Generate a creative story plot.

Genre: Fantasy
Tone: Mysterious & adventurous
World Setting: An ancient forest hiding forgotten magic

Write a 3-paragraph plot:

Story, storyboard, and story.

Format: Word documents.

Date and time: Time in weeks or months

Character name:

Fictional Characters:

Characters (optional):

Story

Storyboard:

Character name:

Plot

Storyboard (optional):

Character name:

Pitch

Plot (optional):

Character name:

Character name:

Storyboard (optional):

Character name:

Characters (optional):

Character name:

Plot

Storyboard (optional):

Character name:

Plot (optional):

Characters (optional):

Character name:

Plot

=== CHARACTER DESCRIPTION ===

[BLOCKED BY SAFETY FILTER]

=== EVALUATION ===

{'length': 80, 'unique_words': 47, 'avg_word_length': 6.875}
